# Generated by Django 3.0.5 on 2020-04-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='read_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='write_permission',
            field=models.BooleanField(default=False),
        ),
    ]
